# -*- coding: utf-8 -*-
"""ahmed_bektas_midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgLVh3opMMRyWP16TB6VeAfS6gC-1o8M

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

# machine learning is an autonomous system that uses algorithm to learn or create something with the help of human as an advisor 
# or without help of a human for advanced versions. machine is learning things by repetition and can redo them or create something orijinal.

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

# face recognition for securitiy systems or photography machines.
# personal assistants like siri and alexa.
# search engines' predictions like google recommedations.

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

# example: a list that include different features and what these features means(correct answer).
# feature: different characteristics of a thing that is in the "example" as correct answer.
# label: the correct answer which is shown with different "features".
# feature vector: n-dimensional vector of numerical features which shows the correct answer.

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

# i believe that AI will make easier our job but won't be a visual communication designer as itself. a lot of thigs that take our times today,
# can be done in seconds maybe in the future but it won't create something creative and original. maybe AI can have it's own ideas in future
# but i don't think that it will have emotions and feelings.

"""Try to describe how you learn in algorithmic terms."""

# i see, hear things that i don't know and someone is explaining me what they are. than when i see or hear them or something like them again,
# i can describe what they are. Also for example, i can recognize things after i see them a lot of times. than i can maybe make something like
# them because i leared what they look like.

"""Create a python dictionary for your name surname and year of birth."""

whoami = {'name': 'ahmed', 'surname': 'bektas', 'birth': 1995}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if whoami['name'][0] == 'a':
  print('my initial is a!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(whoami['surname']) % 3 == 0:
  
  print('it is divisible')

  
else:
  print('not divisible')

"""Change your year of birth to 2678."""

whoami['birth'] = 2678

print(whoami)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

bla = range(20,40)
for numbers in bla:
  if numbers % 5 == 0:
    print(numbers)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

print((0.87 * 0.12) + (0.87 * 0.06) + (0.87 * 0.06) + (0.87 * 0.76 ))

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""
